// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import("@arco-design/web-vue")["Button"]
    Header: typeof import('./src/components/header/Header.vue')['default']
    Lottie: typeof import('./src/components/common/Lottie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./src/components/common/TextButton.vue')['default']
  }
}
