// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import("@arco-design/web-vue")["Avatar"]
    AButton: typeof import("@arco-design/web-vue")["Button"]
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACardMeta: typeof import('@arco-design/web-vue')['CardMeta']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import("@arco-design/web-vue")["SkeletonLine"]
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import("@arco-design/web-vue")["Space"]
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypographyText: typeof import("@arco-design/web-vue")["TypographyText"]
    Header: typeof import('./src/components/header/Header.vue')['default']
    HomeBaseLayout: typeof import("./src/components/home/HomeBaseLayout.vue")["default"]
    HomeTravel: typeof import("./src/components/home/HomeTravel.vue")["default"]
    Lottie: typeof import('./src/components/common/Lottie.vue')['default']
    PictureCard: typeof import('./src/components/picture/PictureCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./src/components/common/TextButton.vue')['default']
  }
}
